import { ProjectTypes } from "@/types";

const projects: ProjectTypes[] = [
  {
    name: "Portfolio",
    mainType: "typescript",
    previewLink: "https://qudusayo.me",
    previewImg: "/projects/portfolio.png",
    category: ["Typescript", "NextJs"],
    description: "My current portfolio website.",
    githubUrl: "https://github.com/Qudusayo/v2portfolio",
  },
  {
    name: "Solvre",
    mainType: "next",
    previewLink: "https://solvre.pro",
    previewImg: "/projects/solvre.png",
    category: ["NextJs", "Typescript"],
    description: "Task Delegation platform.",
  },
  {
    name: "Web3afrika",
    mainType: "react",
    previewLink: "https://web3afrika.com",
    previewImg: "/projects/web3afrika.png",
    category: ["React", "Contribution"],
    description: "Official Website for Web3Afrika.",
    githubUrl: "https://github.com/Web3Afrika/web3afrika.com-v2",
  },
  {
    name: "RionNigeria",
    previewLink: "https://rionnigeria.org/",
    mainType: "next",
    previewImg: "/projects/rionnigeria.png",
    category: ["NextJs", "Typescript"],
    description: "RION Nigeria website redesign",
  },
  {
    name: "Metaangels Clone",
    previewLink: "https://marketplace.qudusayo.me/",
    mainType: "react",
    previewImg: "/projects/metaangels.png",
    category: ["React", "Blockchain"],
    description: "Meta Angels marketplace UI clone",
    githubUrl: "https://github.com/Qudusayo/nft-marketplace",
  },
  {
    name: "Revoke",
    previewLink: "https://revoke-theta.vercel.app/",
    mainType: "next",
    previewImg: "/projects/revoke.png",
    category: ["Next", "Blockchain", "Typescript"],
    description: "Token approvals revoke.",
    githubUrl: "https://github.com/Qudusayo/revoke",
  },
  {
    name: "Article Idea Generator",
    previewLink: "https://www.articleideagenerator.com/",
    mainType: "react",
    previewImg: "/projects/articleideagenerator.png",
    category: ["React", "Contribution"],
    description: "AI tool to generate article ideas",
    githubUrl: "https://github.com/Olanetsoft/article-idea-generator/pull/41",
  },
  {
    name: "BuyMeCoffee",
    previewLink: "https://buymeacoffee.qudusayo.me/",
    mainType: "react",
    previewImg: "/projects/buymeacoffee.png",
    category: ["React", "Blockchain"],
    description: "Onchain based tipping platform",
    githubUrl: "https://github.com/qudusayo/buymecoffee",
  },
  {
    name: "web3Terms",
    previewLink: "https://github.com/Olanetsoft/web3terms",
    mainType: "contribution",
    previewImg: "/projects/web3terms.png",
    category: ["NodeJs", "Contribution", "Blockchain"],
    description: "web3 twitter bot!",
    githubUrl:
      "https://github.com/Olanetsoft/web3terms/commits?author=Qudusayo",
  },
  {
    name: "devFinder",
    previewLink: "https://gh-user-sa.qudusayo.me/",
    mainType: "react",
    previewImg: "/projects/githubprofile.png",
    category: ["React", "Typescript"],
    description: "Github user profile summary check",
    githubUrl: "https://github.com/Qudusayo/github-user-search-app",
  },
  {
    name: "Quiz",
    previewLink: "https://general-studies-practice.vercel.app/",
    mainType: "next",
    previewImg: "/projects/gesquiz.png",
    category: ["NextJs", "Typescript"],
    description: "Exam practice application",
    githubUrl: "https://github.com/Qudusayo/pq-practice-app",
  },
  {
    name: "GoFanClub Minter",
    previewLink: "https://nfts.gofanclub.com/",
    mainType: "react",
    previewImg: "/projects/nftgofanclub.png",
    category: ["React", "Blockchain"],
    description: "NFT minter",
  },
];

export default projects;
