import { ProjectTypes } from "@/types";

const projects: ProjectTypes[] = [
  {
    name: "Metaangels Clone",
    previewLink: "https://marketplace.qudusayo.me/",
    mainType: "react",
    previewImg: "/projects/metaangels.png",
    category: ["React", "Blockchain"],
    description: "Meta Angels nft marketplace UI clone",
    githubUrl: "https://github.com/Qudusayo/nft-marketplace",
  },
  {
    name: "Portfolio",
    mainType: "typescript",
    previewLink: "https://qudusayo.me",
    previewImg: "/projects/portfolio.png",
    category: ["Typescript", "NextJs"],
    description: "My current portfolio website.",
    githubUrl: "https://github.com/Qudusayo/v2portfolio",
  },
  {
    name: "Web3afrika",
    mainType: "react",
    previewLink: "https://web3afrika.com",
    previewImg: "/projects/web3afrika.png",
    category: ["React", "OpenSource"],
    description: "Official Website for Web3Afrika.",
    githubUrl: "https://github.com/Web3Afrika/web3afrika.com-v2",
  },
  {
    name: "RionNigeria",
    previewLink: "https://rionnigeria.vercel.app/",
    mainType: "next",
    previewImg: "/projects/rionnigeria.png",
    category: ["NextJs", "Typescript"],
    description: "RION Nigeria website redesign",
  },
  {
    name: "Revoke",
    previewLink: "https://revoke-theta.vercel.app/",
    mainType: "next",
    previewImg: "/projects/revoke.png",
    category: ["Next", "Blockchain", "Typescript"],
    description: "Review and revoke your token approvals.",
    githubUrl: "https://github.com/Qudusayo/revoke",
  },
  {
    name: "Article Idea Generator",
    previewLink: "https://www.articleideagenerator.com/",
    mainType: "react",
    previewImg: "/projects/articleideagenerator.png",
    category: ["React", "Blockchain"],
    description: "An AI tool to generate article ideas",
    githubUrl: "https://github.com/Olanetsoft/article-idea-generator/pull/41",
  },
  {
    name: "BuyMeCoffee",
    previewLink: "https://buymeacoffee.qudusayo.me/",
    mainType: "react",
    previewImg: "/projects/buymeacoffee.png",
    category: ["React", "Blockchain"],
    description: "Blockchain buy me a coffee tipping page",
    githubUrl: "https://github.com/qudusayo/buymecoffee",
  },
  {
    name: "web3Terms",
    previewLink: "https://github.com/Olanetsoft/web3terms",
    mainType: "opensource",
    previewImg: "/projects/web3terms.png",
    category: ["NodeJs", "OpenSource", "Blockchain"],
    description: "A Twitter bot explaining web3 terms to everyone!",
    githubUrl: "https://github.com/olanetsoft/web3terms",
  },
  {
    name: "devFinder",
    previewLink: "https://gh-user-sa.qudusayo.me/",
    mainType: "react",
    previewImg: "/projects/githubprofile.png",
    category: ["React", "Typescript"],
    description: "Github user profile summary check",
    githubUrl: "https://github.com/Qudusayo/github-user-search-app",
  },
  {
    name: "Quiz",
    previewLink: "https://general-studies-practice.vercel.app/",
    mainType: "next",
    previewImg: "/projects/gesquiz.png",
    category: ["NextJs", "Typescript"],
    description: "Exam practice application for students",
    githubUrl: "https://github.com/Qudusayo/pq-practice-app",
  },
  {
    name: "GoFanClub Minter",
    previewLink: "https://nfts.gofanclub.com/",
    mainType: "react",
    previewImg: "/projects/nftgofanclub.png",
    category: ["React", "Blockchain"],
    description: "Onchain NFT minter through image upload",
  },
];

export default projects;
